version: '3.8'

services:
  app:
    build: .
    container_name: bitcoin-trading-app
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - AWS_REGION=ap-northeast-2
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - bitcoin-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: bitcoin-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - bitcoin-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: bitcoin-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - bitcoin-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    container_name: bitcoin-logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/logs
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - bitcoin-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  bitcoin-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local